### ISSUE TITLE
nant test fails on Appveyor for Budget tests

### ISSUE THREAD

**Issue by tpokorra** [openpetra/openpetra#127]
see https://ci.appveyor.com/project/tpokorra/openpetra/build/1.0.111

```

Testing C:\projects\openpetra\delivery\bin/Ict.Testing.lib.MFinance.server.Budget.dll 
NUnit-Console version 2.6.1.12217
Copyright (C) 2002-2012 Charlie Poole.
Copyright (C) 2002-2004 James W. Newkirk, Michael C. Two, Alexei A. Vorontsov.
Copyright (C) 2000-2002 Philip Craig.
All Rights Reserved.

Runtime Environment - 
   OS Version: Microsoft Windows NT 6.2.9200.0
  CLR Version: 2.0.50727.8009 ( Net 3.5 )

ProcessModel: Default    DomainUsage: Single
Execution Runtime: net-3.5
***** Ict.Testing.Petra.Server.MFinance.Budget.TestBudget.T0_Consolidation
***** Ict.Testing.Petra.Server.MFinance.Budget.TestBudget.T1_AutoGenerationLoadData
***** Ict.Testing.Petra.Server.MFinance.Budget.TestBudget.T2_AutoGenerationGenBudget
***** Ict.Testing.Petra.Server.MFinance.Budget.TestBudget.T4_AutoGenerationSetBudgetAmount

Tests run: 4, Errors: 1, Failures: 1, Inconclusive: 0, Time: 1.3827976 seconds
  Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0

Errors and Failures:
1) Test Error : Ict.Testing.Petra.Server.MFinance.Budget.TestBudget.T0_Consolidation
   System.Exception : Nant did not succeed
   at Ict.Testing.NUnitTools.CommonNUnitFunctions.nant(String argument, Boolean ignoreError) in c:\projects\openpetra\csharp\ICT\Testing\lib\NUnitTools\CommonNUnitFunctions.cs:line 342
   at Ict.Testing.NUnitTools.CommonNUnitFunctions.ResetDatabase() in c:\projects\openpetra\csharp\ICT\Testing\lib\NUnitTools\CommonNUnitFunctions.cs:line 113
   at Ict.Testing.Petra.Server.MFinance.Budget.TestBudget.T0_Consolidation() in c:\projects\openpetra\csharp\ICT\Testing\lib\MFinance\server\Budget\Test.Budget.cs:line 84

2) Test Failure : Ict.Testing.Petra.Server.MFinance.Budget.TestBudget.T1_AutoGenerationLoadData
     Empty Budget Autogeneration Tables: ABudgetRevision; ABudget; ABudgetPeriod; 
  Expected: <empty>
  But was:  "ABudgetRevision; ABudget; ABudgetPeriod; "

at Ict.Testing.Petra.Server.MFinance.Budget.TestBudget.T1_AutoGenerationLoadData() in c:\projects\openpetra\csharp\ICT\Testing\lib\MFinance\server\Budget\Test.Budget.cs:line 255


21:02:48      Connecting to database SQLite: Data Source=C:\projects\openpetra\delivery\sqlite\work.db*hidden*
21:02:48  Client 'DEMO' is connecting...
21:02:48  Client 'DEMO' successfully connected. ClientID: 0
21:02:49  Object reference not set to an instance of an object.
21:02:49  BeginTransaction: Attempting to reconnect to the database as the DB connection isn't available! (FSqlConnection is null!)
21:02:49      Connecting to database SQLite: Data Source=C:\projects\openpetra\delivery\sqlite\work.db*hidden*
21:02:49  EndSession (for client 'DEMO_0'): Session is about to getting stopped!
21:02:49  EndSession (for client 'DEMO_0'): Checking whether there is a DB connection
21:02:49  EndSession (for client 'DEMO_0'): Closing DB connection
21:02:49  EndSession (for client 'DEMO_0'): Checking whether there is a HttpSession.Current object


            BUILD FAILED

            INTERNAL ERROR

            System.Exception: Exit Code 2 shows that something went wrong
               at Ict.Tools.NAntTasks.NUnitConsoleTask.ExecuteTask()
               at NAnt.Core.Task.Execute()
               at NAnt.Core.Target.Execute()
               at NAnt.Core.Project.Execute(String targetName, Boolean forceDependencies)
               at NAnt.Core.Tasks.CallTask.ExecuteTask()
               at NAnt.Core.Task.Execute()
               at NAnt.Core.Target.Execute()
               at NAnt.Core.Project.Execute(String targetName, Boolean forceDependencies)
               at NAnt.Core.Tasks.CallTask.ExecuteTask()
               at NAnt.Core.Task.Execute()
               at NAnt.Core.Target.Execute()
               at NAnt.Core.Project.Execute(String targetName, Boolean forceDependencies)
               at NAnt.Core.Project.Execute()
               at NAnt.Core.Project.Run()

            Please send bug report to nant-developers@lists.sourceforge.net.

            Total time: 29.5 seconds.


BUILD FAILED - 0 non-fatal error(s), 4 warning(s)

Nested build failed.  Refer to build log for exact reason.

Total time: 42.5 seconds.
```

**Comment by tpokorra** [comment]
appveyor tests now run on Ubuntu, all tests have been enabled again.
