### ISSUE TITLE
sqlite: to_char, in GetReceivingFields

### ISSUE THREAD

**Issue by tpokorra** [openpetra/openpetra#37]
see https://ci-win.openpetra.org/job/OpenpetraBuildTestWinSQLite_MainNavigationScreens/122/parsed_console/

```
03:15:46 Window can't be opened: DonorGiftsToFieldsReport TFrmDonorGiftsToFieldsReport

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Ict.Common.Exceptions.EOPDBException: [Context: Error fetching records.] ---> Mono.Data.Sqlite.SqliteException: SQLite error

no such function: to_char

at Mono.Data.Sqlite.SQLite3.Prepare(SqliteConnection cnn, String strSql, SqliteStatement previous, UInt32 timeoutMS, String& strRemain)

at Mono.Data.Sqlite.SqliteCommand.BuildNextCommand()

at Mono.Data.Sqlite.SqliteCommand.GetStatement(Int32 index)

at Mono.Data.Sqlite.SqliteDataReader.NextResult()

at Mono.Data.Sqlite.SqliteDataReader..ctor(SqliteCommand cmd, CommandBehavior behave)

at Mono.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)

at Mono.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)

at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)

at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)

at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)

at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)

at Ict.Common.DB.TSQLite.FillAdapter(DbDataAdapter TheAdapter, DataTable& AFillDataTable, Int32 AStartRecord, Int32 AMaxRecords) in c:\Program Files (x86)\Jenkins\OpenpetraBuildTestWinSQLite\csharp\ICT\Common\DB\SQLite.cs:line 350

at Ict.Common.DB.TDataBase.SelectDTInternal(String ASqlStatement, String ADataTableName, TDBTransaction AReadTransaction, DbParameter[] AParametersArray) in c:\Program Files (x86)\Jenkins\OpenpetraBuildTestWinSQLite\csharp\ICT\Common\DB\Access.cs:line 1202

--- End of inner exception stack trace ---



Server stack trace: 

at Ict.Common.DB.TDataBase.LogException(Exception AException, String ASqlStatement, DbParameter[] AParametersArray, String AContext, Boolean AThrowExceptionAfterLogging) in c:\Program Files (x86)\Jenkins\OpenpetraBuildTestWinSQLite\csharp\ICT\Common\DB\Access.cs:line 2659

at Ict.Common.DB.TDataBase.LogExceptionAndThrow(Exception AException, String ASqlStatement, DbParameter[] AParametersArray, String AContext) in c:\Program Files (x86)\Jenkins\OpenpetraBuildTestWinSQLite\csharp\ICT\Common\DB\Access.cs:line 2552

at Ict.Common.DB.TDataBase.SelectDTInternal(String ASqlStatement, String ADataTableName, TDBTransaction AReadTransaction, DbParameter[] AParametersArray) in c:\Program Files (x86)\Jenkins\OpenpetraBuildTestWinSQLite\csharp\ICT\Common\DB\Access.cs:line 1214

at Ict.Common.DB.TDataBase.SelectDT(String ASqlStatement, String ADataTableName, TDBTransaction AReadTransaction) in c:\Program Files (x86)\Jenkins\OpenpetraBuildTestWinSQLite\csharp\ICT\Common\DB\Access.cs:line 1140

at Ict.Petra.Server.MFinance.Reporting.WebConnectors.TFinanceReportingWebConnector.<>c__DisplayClass13.<GetReceivingFields>b__12() in c:\Program Files (x86)\Jenkins\OpenpetraBuildTestWinSQLite\csharp\ICT\Petra\Server\lib\MFinance\GL\Reporting.UIConnectors.cs:line 147

at Ict.Common.DB.TDataBase.GetNewOrExistingAutoReadTransaction(IsolationLevel ADesiredIsolationLevel, TEnforceIsolationLevel ATryToEnforceIsolationLevel, TDBTransaction& ATransaction, Action AEncapsulatedDBAccessCode) in c:\Program Files (x86)\Jenkins\OpenpetraBuildTestWinSQLite\csharp\ICT\Common\DB\Access.cs:line 3007

at Ict.Petra.Server.MFinance.Reporting.WebConnectors.TFinanceReportingWebConnector.GetReceivingFields(Int32 ALedgerNumber, String& ADisplayMember, String& AValueMember) in c:\Program Files (x86)\Jenkins\OpenpetraBuildTestWinSQLite\csharp\ICT\Petra\Server\lib\MFinance\GL\Reporting.UIConnectors.cs:line 129
```

**Comment by tpokorra** [comment]
see also https://github.com/openpetra/openpetra/blob/master/csharp/ICT/Petra/Server/lib/MFinance/GL/Reporting.GiftReports.UIConnectors.cs, MotivationResponse, which still uses to_char.

It has been worked around in https://github.com/openpetra/openpetra/blob/master/csharp/ICT/Petra/Server/lib/MFinance/AP/AP.Find.cs PerformSearch

I cannot find though the original problem in TFinanceReportingWebConnector anymore.

**Comment by tpokorra** [comment]
we don't support sqlite anymore
