### ISSUE TITLE
Can't add Family/Person/Venue and so on

### ISSUE THREAD

**Issue by Gziri** [openpetra/openpetra#60]
Error after every attempt to add anyone to Partners was:

System.IndexOutOfRangeException: There is no row at position 0.
   at System.Data.RBTree`1.GetNodeByIndex(Int32 userIndex)
   at System.Data.DataRowCollection.get_Item(Int32 index)
   at Ict.Petra.Shared.MPartner.Partner.Data.PPartnerTable.get_Item(Int32 i)
   at Ict.Petra.Client.MPartner.Gui.TFrmPartnerEdit.LoadData()
   at Ict.Petra.Client.MPartner.Gui.TFrmPartnerEdit.TFrmPartnerEdit2_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
--------------------------------------
OpenPetra Version 2014.12.0.0
Date/Time: 30/04/2015 22:13:52 (UTC: Thu, 30 Apr 2015 18:13:52 GMT)

**Comment by tpokorra** [comment]
I can reproduce this.
in the log file in `AppData\OpenPetra.org\tmp30\PetraClient.log`, I have:

```
Dienstag, 05-Mai-2015, 11:44:14.56 [DEMO_0] : Exception occured in GetDataNewPartner: System.NullReferenceException: Object reference not set to an instance of an object.
   at Ict.Petra.Server.MPartner.Partner.UIConnectors.TPartnerEditUIConnector.GetDataNewPartner(Int64 ASiteKey, Int64 APartnerKey, TPartnerClass APartnerClass, String ADesiredCountryCode, String AAcquisitionCode, Boolean APrivatePartner, Int64 AFamilyPartnerKey, Int64 AFamilySiteKey, Int32 AFamilyLocationKey, String& ASiteCountryCode)
```

I will look into this, thanks for reporting it!

**Comment by tpokorra** [comment]
@Gziri If you want, you can test the latest standalone installer available at https://lbs.solidcharity.com/package/tpokorra/openpetra/openpetranow-standalone

**Comment by Gziri** [comment]
Hello Mrs. Pokorra,

I am a founder of Association of Physiatrists of Georgia. Our main aim is
to develop physical medicine and rehabilitation in Georgia and all other
stuff connected to it.

I have to tell that despite of that OpenPetra is a grate project, it can't
support most of NGO's administration needs at least in Georgia (Where
Europe meets Asia). I regret that don't know C# to configure OpenPetra, but
i have good ideas about it.

My team and I were looking for a volunteer who could change some things in
software for us, but unfortunately we could not find such person (We are
looking for volunteers because of lack of funds). If you know such person
or you do want to know what I would add or change in OpenPetra, I well be
happy to work hard to make OpenPetra better for every NGO/Non-profit.

And for last - the software still has errors but only on my Desktop PC, it
works fine on my Laptop.

Sincerely,

Gela Gzirishvili

*გელა გზირიშვილი*
*Gela Gzirishvili*

**Comment by tpokorra** [comment]
Hello Gela,

please note that this conversation is public, at https://github.com/openpetra/openpetra/issues/60

You are welcome to file bugs, and feature requests here in this issue tracker: 
https://github.com/openpetra/openpetra/issues

Please create a new ticket about the errors on your Desktop PC.
I cannot guarantuee that they will be fixed, and how soon. But I will try to look at it.

You can contribute by finding bugs and testing if the solution works. This is how Open Source works :)

I was busy with other projects in the past months, but I hope to focus on OpenPetra more again.

All the best,
  Timotheus
