### ISSUE TITLE
Standalone sqlite: cannot save new partner, typed table problem

### ISSUE THREAD

**Issue by tpokorra** [openpetra/openpetra#63]
this is on my branch fixing standalone for OpenPetra master.
see line https://github.com/openpetra/openpetra/blob/master/csharp/ICT/Petra/Client/MPartner/Gui/UC_ContactDetails.ManualCode.cs#L396

```
System.InvalidCastException: Unable to cast object of type 'System.Data.DataTable' to type 'Ict.Petra.Shared.MPartner.Partner.Data.PPartnerAttributeCategoryTable'.
   at Ict.Petra.Client.MPartner.Gui.TUC_ContactDetails.InitializeManualCode()
   at Ict.Petra.Client.MPartner.Gui.TUC_ContactDetails.InitUserControl()
   at Ict.Petra.Client.MPartner.Gui.TUC_PartnerEdit_PartnerTabSet.SetupUserControlContactDetails()
   at Ict.Petra.Client.MPartner.Gui.TUC_PartnerEdit_PartnerTabSet.CleanupRecordsBeforeMerge()
   at Ict.Petra.Client.MPartner.Gui.TUC_PartnerEdit_LowerPart.CleanupAddressesBeforeMerge()
   at Ict.Petra.Client.MPartner.Gui.TFrmPartnerEdit.SaveChanges(PartnerEditTDS& AInspectDS)
   at Ict.Petra.Client.MPartner.Gui.TFrmPartnerEdit.SaveChanges(PartnerEditTDS& AInspectDS)
   at Ict.Petra.Client.MPartner.Gui.TFrmPartnerEdit.FileSave(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by tpokorra** [comment]
debugging https://github.com/openpetra/openpetra/blob/master/csharp/ICT/Petra/Shared/CacheableTablesManager.cs#L1385

line 1401 returns a DataTable, untyped

**Comment by tpokorra** [comment]
see the fix from Alan. need to delete the old cache files in IsolatedStorage
